### ISSUE TITLE
How to best benchmark LinqOptimizer?

### ISSUE THREAD

**Issue by aalmada** [nessos/LinqOptimizer#13]
I created a repository with benchmarks that compare the performance of several LINQ-to-Objects implementations. It can be found at https://github.com/NetFabric/LinqBenchmarks

It includes both LinqOptimizer and Streams. I think I implemented them as you have in here but I'm getting the huge hit in  performance because of the first iteration. 

Am I doing something wrong?

**Comment by palladin** [comment]
I think that you need to pre-compile the queries
Check https://github.com/biboudis/clashofthelambdas/blob/master/csharp/ClashOfLambdas.cs#L79 and
https://github.com/nessos/LinqOptimizer/blob/master/src/LinqOptimizer.CSharp/Extensions.cs#L35
